name: Build Android APK

on:
  push:
    branches: [ "standalone" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Android SDK & NDK
        uses: actions/setup-android@v3

      - name: Build Debug APK
        run: |
          cd android-project
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: BetterSpades-Android
          path: android-project/app/build/outputs/apk/debug/*.apk
